### ISSUE TITLE
Program crashes when modifying book that is not in database

### ISSUE THREAD

**Issue by Anachronaut** [Anachronaut/readinglist#4]
To reproduce:
Start program
Enter 6 to change book read status
Enter any ID that is not in the database
Program crashes with the following stack trace

```
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    main()
  File "main.py", line 16, in main
    action()
  File "main.py", line 63, in change_read
    book = store.get_book_by_id(book_id)
  File "D:\Ben\Documents\Python\Project2\readinglist\bookstore.py", line 181, in get_book_by_id
    return book
UnboundLocalError: local variable 'book' referenced before assignment

```

You'll need to fix Bookstore.get_book_by_id to return None if the book is not found. Also modify main.py to check if the book is found or not before modifying.

**Comment by Anachronaut** [comment]
@crantz007 please check missing_book_crash branch for updated code (main.py, bookstore.py), seems to work

**Comment by Anachronaut** [comment]
Branch merged
